-- Jalankan seluruh script ini di Supabase SQL Editor.
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null default current_date,
  type text not null check (type in ('income','expense')),
  amount numeric(15,2) not null check (amount > 0),
  category text not null,
  wallet text not null check (wallet in ('bersama','hilal','pasangan')),
  note text,
  created_at timestamptz not null default now()
);

alter table public.transactions enable row level security;

drop policy if exists "users can read own transactions" on public.transactions;
create policy "users can read own transactions"
on public.transactions for select
using (auth.uid() = user_id);

drop policy if exists "users can insert own transactions" on public.transactions;
create policy "users can insert own transactions"
on public.transactions for insert
with check (auth.uid() = user_id);

drop policy if exists "users can update own transactions" on public.transactions;
create policy "users can update own transactions"
on public.transactions for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users can delete own transactions" on public.transactions;
create policy "users can delete own transactions"
on public.transactions for delete
using (auth.uid() = user_id);

-- Catatan penting:
-- Versi awal ini mengamankan data per akun.
-- Agar dua akun bisa melihat SATU dompet bersama, langkah berikutnya adalah
-- menambahkan tabel household/members dan policy berbasis household_id.
